import { MaterialDetail } from './types';

export const materialsData: MaterialDetail[] = [
  {
    id: "01",
    title: "Bagian - 1",
    subTitle: "Pengantar Kitab Thaharah & Definisi Syariat",
    arabicText: "وَالْكِتَابُ لُغَةً مَصْدَرٌ بِمَعْنَى الضَّمِّ وَالْجَمْعِ، وَاصْطِلَاحاً اسْمٌ لِجِنْسٍ مِنَ الْأَحْكَامِ. أَمَّا الْبَابُ فَاسْمٌ لِنَوْعٍ مِمَّا دَخَلَ تَحْتَ ذَلِكَ الْجِنْسِ. وَالطَّهَارَةُ بِفَتْحِ الطَّاءِ لُغَةً النَّظَافَةُ، وَأَمَّا شَرْعاً فَفِيهَا تَفَاسِيرُ كَثِيرَةٌ؛ مِنْهَا قَوْلُهُمْ فِعْلُ مَا تَسْتَبَاحُ بِهِ الصَّلَاةُ، أَيْ مِنْ وُضُوءٍ وَغُسْلٍ وَتَيَمُّمٍ وَإِزَالَةِ نَجَاسَةٍ. أَمَّا الطَّهَارَةُ بِالضَّمِّ، فَاسْمٌ لِبَقِيَّةِ الْمَاءِ. وَلَمَّا كَانَ الْمَاءُ آلَةً لِلطَّهَارَةِ اسْتَطْرَدَ الْمُصَنِّفُ لِأَنْوَاعِ الْمِيَاهِ.",
    translationIndo: "Kitab secara bahasa adalah bentuk masdar yang bermakna mengumpulkan dan menyatukan. Sedangkan menurut istilah, kitab adalah nama untuk sekumpulan hukum-hukum. Adapun bab adalah nama untuk jenis tertentu yang masuk di bawah cakupan hukum tersebut. Thaharah (dengan fathah huruf Tha') secara bahasa berarti bersuci/kebersihan. Sedangkan menurut syara' terdapat banyak penafsiran, di antaranya adalah: Melakukan sesuatu yang menjadikan shalat sah, seperti wudhu, mandi, tayamum, dan mensucikan najis. Adapun Thuharah (dengan dhammah huruf Tha') adalah nama bagi sisa air. Karena air merupakan alat utama bersuci, maka penulis menjabarkan macam-macam air.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 1 & 4 (Identifikasi Kalimat & Marfu'at): Kata 'Al-Kitabu' diidentifikasi sebagai Kalimat Isim karena diawali Alif Lam (الـ). Statusnya adalah Isim Mu'rob (berubah harokat akibat amil). Dalam tarkib kalimat, ia berkedudukan sebagai Mubtada' (Subjek) yang dibaca Rofa' dengan tanda dhommah, sedangkan kata 'Masdarun' berkedudukan sebagai Khobar (Predikat) yang melengkapi maknanya.",
    analysisSample: [
      { word: "وَالْكِتَابُ", transliteration: "wal-kitābu", translation: "Dan kitab itu", grammarRole: "Mubtada' (Subjek)", explanation: "Merupakan isim ma'rifah karena memiliki alif lam (al-), berkedudukan sebagai subjek kalimat." },
      { word: "لُغَةً", transliteration: "lughatan", translation: "secara bahasa", grammarRole: "Mansub / Tamyiz", explanation: "Menerangkan batasan makna kata 'al-Kitab' dari segi kebahasaan." },
      { word: "مَصْدَرٌ", transliteration: "maṣdarun", translation: "adalah bentuk masdar", grammarRole: "Khobar (Predikat)", explanation: "Isim nakiroh berharakat dhammah dua, berkedudukan sebagai predikat yang melengkapi keterangan mubtada'." },
      { word: "بِمَعْنَى", transliteration: "bima'nā", translation: "dengan arti", grammarRole: "Jarr Majrur", explanation: "Terdiri dari huruf jarr 'bi' dan isim majrur 'ma'na'." },
      { word: "الضَّمِّ", transliteration: "ad-ḍammi", translation: "mengumpulkan", grammarRole: "Mudhaf Ilaih", explanation: "Isim yang dijatuhkan setelah mudhaf untuk menunjukkan kepemilikan atau spesifikasi makna." }
    ]
  },
  {
    id: "02",
    title: "Bagian - 2",
    subTitle: "Tujuh Macam Air & Pembagian Derajat Air",
    arabicText: "أَيْ يَصِحُّ (التَّطْهِيرُ بِهَا سَبْعُ مِيَاهٍ: مَاءُ السَّمَاءِ) أَيْ (الْمِيَاهُ الَّتِي يَجُوزُ) النَّازِلُ مِنْهَا، وَهُوَ الْمَطَرُ (وَمَاءُ الْبَحْرِ) أَيْ الْمِلْحُ، (وَمَاءُ النَّهْرِ) أَيْ الْحُلْوُ (وَمَاءُ الْبِئْرِ، وَمَاءُ الْعَيْنِ، وَمَاءُ الثَّلْجِ، وَمَاءُ الْبَرَدِ). وَيَجْمَعُ هَذِهِ السَّبْعَةَ قَوْلُكَ: مَا نَزَلَ مِنَ السَّمَاءِ أَوْ نَبَعَ مِنَ الْأَرْضِ عَلَى أَيِّ صِفَةٍ كَانَ مِنْ أَصْلِ الْخِلْقَةِ. ثُمَّ الْمِيَاهُ) تَنْقَسِمُ (عَلَى أَرْبَعَةِ أَقْسَامٍ): أَحَدُهَا (طَاهِرٌ) فِي نَفْسِهِ (مُطَهِّرٌ) لِغَيْرِهِ (غَيْرُ مَكْرُوهٍ اسْتِعْمَالُهُ، وَهُوَ الْمَاءُ الْمُطْلَقُ) عَنْ قَيْدٍ لَازِمٍ； فَلَا يَضُرُّ الْقَيْدُ الْمُنْفَكُّ كَمَاءِ الْبِئْرِ فِي كَوْنِهِ مُطْلَقاً.",
    translationIndo: "Yaitu sah bersuci menggunakan tujuh air: air langit (yaitu air yang boleh digunakan yang turun dari langit, yakni air hujan), air laut (yaitu air asin), air sungai (yaitu air tawar), air sumur, air sumber/mata air, air salju, dan air es (hujan es). Ketujuh sumber air ini dirangkum dalam ucapanmu: 'Segala apa yang turun dari langit atau memancar dari bumi dalam keadaan apapun sesuai dengan sifat asli penciptaannya.' Kemudian air dibagi menjadi empat bagian: Pertama, air Suci dan Mensucikan bagi yang lain serta tidak makruh penggunaannya, yaitu Air Mutlak (bebas dari ikatan nama yang lazim, sehingga penyebutan tidak mengikat seperti sebutan air sumur tidak menghalanginya untuk disebut air secara mutlak).",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 2 & 3 (Ma'rifat-Nakirah & Jenis Fi'il): Kata 'Ma-u' diidentifikasi sebagai Isim Ma'rifat karena dijadikan mudhaf (sandaran) ke kata setelahnya 'as-Sama-i' yang memiliki Alif Lam. Konstruksi ini dinamakan Idhafah Ma'nawiyah. Kata 'Yasihhu' adalah Fi'il Mudhari' Mu'rob karena bersih dari amil nashob/jazem, wajib dibaca Rofa' dengan tanda dhommah, dan membutuhkan Isim Marfu' 'at-Tathhiru' sebagai Fa'il-nya.",
    analysisSample: [
      { word: "يَصِحُّ", transliteration: "yaṣiḥḥu", translation: "adalah sah", grammarRole: "Fi'il Mudhari'", explanation: "Kata kerja masa sekarang/akan datang yang diawali huruf mudhara'ah ya', berharokat rafa'." },
      { word: "التَّطْهِيرُ", transliteration: "at-taṭhīru", translation: "mensucikan", grammarRole: "Fa'il (Pelaku)", explanation: "Kata benda pelaku dari perbuatan sah, merupakan bentuk isim masdar dari Thohharo." },
      { word: "سَبْعُ", transliteration: "sab'u", translation: "tujuh", grammarRole: "Mudhaf / Adad", explanation: "Bilangan pembatas (adad) yang membutuhkan objek yang dihitung (ma'dud) berupa miyahin." },
      { word: "مِيَاهٍ", transliteration: "miyāhin", translation: "jenis air", grammarRole: "Mudhaf Ilaih", explanation: "Bentuk jamak taksir dari kata 'ma'un' (air), berkedudukan as mudhaf ilaih." }
    ]
  },
  {
    id: "03",
    title: "Bagian - 3",
    subTitle: "Hukum Air Musyammas & Air Musta'mal",
    arabicText: "الثَّانِي (طَاهِرٌ) فِي نَفْسِهِ (مُطَهِّرٌ) لِغَيْرِهِ (مَكْرُوهٌ اسْتِعْمَالُهُ) فِي (و) الْبَدَنِ، لَا فِي الثَّوْبِ؛ (وَهُوَ الْمَاءُ الْمُشَمَّسُ) أَيْ الْمُسَخَّنُ بِتَأْثِيرِ الشَّمْسِ فِيهِ. وَإِنَّمَا يُكْرَهُ شَرْعاً بِقُطْرٍ حَارٍّ فِي إِنَاءٍ مُنْطَبِعٍ إِلَّا إِنَاءَ النَّقْدَيْنِ لِصَفَاءِ جَوْهَرِهِمَا. وَإِذَا بَرَدَ زَالَتِ الْكَرَاهَةُ. وَاخْتَارَ النَّوَوِيُّ عَدَمَ الْكَرَاهَةِ مُطْلَقاً. وَيُكْرَهُ أَيْضاً شَدِيدُ السُّخُونَةِ وَالْبُرُودَةِ. (وَ) الْقِسْمُ الثَّالِثُ (طَاهِرٌ) فِي نَفْسِهِ (غَيْرُ مُطَهِّرٍ لِغَيْرِهِ، وَهُوَ الْمَاءُ الْمُسْتَعْمَلُ) فِي رَفْعِ حَدَثٍ أَوْ إِزَالَةِ نَجَسٍ إِنْ لَمْ يَتَغَيَّرْ وَلَمْ يَزِدْ وَزْنُهُ بَعْدَ انْفِصَالِهِ عَمَّا كَانَ بَعْدَ اعْتِبَارِ مَا يَتَشَرَّبُهُ الْمَغْسُولُ مِنَ الْمَاءِ؛",
    translationIndo: "Bagian kedua adalah air Suci dan Mensucikan namun Makruh digunakan pada tubuh (bukan pada pakaian), yaitu Air Musyammas (yang dipanaskan oleh terik matahari). Kemakruhan ini berlaku jika air berada di wilayah beriklim panas dan di dalam wadah logam yang dapat ditempa selain wadah emas dan perak karena jernihnya unsur logam tersebut. Jika air telah dingin, kemakruhan tersebut hilang. Imam Nawawi berpendapat mutlak tidak makruh. Makruh juga memakai air yang sangat panas atau sangat dingin. Bagian ketiga: Air Suci namun Tidak Mensucikan, yaitu Air Musta'mal (air yang telah dipakai) untuk menghilangkan hadats atau mensucikan najis, dengan catatan tidak berubah sifatnya dan tidak bertambah volumenya setelah terpisah dari bagian tubuh yang dibasuh.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 2 & 4 (Mudzakkar-Muannats & Na'at): Kata 'Al-Ma-u' bersifat Mudzakkar, maka kata pengikutnya yang menjadi Na'at (sifat) seperti 'Al-Musyammasu' wajib dalam bentuk Mudzakkar pula untuk mufaqat (persesuaian jenis). Kata 'Ath-Thani' berkedudukan sebagai Mubtada' yang dibaca Rofa' (Muqoddor karena berat mengucapkan dhommah di ujung huruf ya), dan 'Thahirun' berkedudukan sebagai Khobar-nya.",
    analysisSample: [
      { word: "الثَّانِي", transliteration: "at-thānī", translation: "Jenis kedua", grammarRole: "Mubtada'", explanation: "Menunjukkan urutan pembagian air." },
      { word: "طَاهِرٌ", transliteration: "ṭāhirun", translation: "adalah suci", grammarRole: "Khobar", explanation: "Status air tersebut bersih dari kotoran." },
      { word: "مَكْرُوهٌ", transliteration: "makrūhun", translation: "hukumnya makruh", grammarRole: "Sifat / Khobar Tsani", explanation: "Pelaku utama akan mendapat pahala bila meninggalkannya dan tidak berdosa bila menggunakannya." },
      { word: "الْبَدَنِ", transliteration: "al-badani", translation: "badan / jasad", grammarRole: "Majrur", explanation: "Didahului oleh huruf jarr 'Fi', menerangkan organ tubuh biologis luar." }
    ]
  },
  {
    id: "04",
    title: "Bagian - 4",
    subTitle: "Hukum Air Mutanajjis (Kemasukan Najis)",
    arabicText: "الْقِسْمُ الرَّابِعُ (مَاءٌ نَجِسٌ) أَيْ مُتَنَجِّسٌ، وَهُوَ قِسْمَانِ: أَحَدُهُمَا (وَهُوَ (وَ) الَّذِي حَلَّتْ فِيهِ نَجَاسَةٌ) تَغَيَّرَ أَمْ لَا، (وَهُوَ) أَيْ وَالْحَالُ أَنَّهُ مَاءٌ (دُونَ الْقُلَّتَيْنِ). وَيُسْتَثْنَى مِنْ هَذَا الْقِسْمِ الْمَيْتَةُ الَّتِي لَا دَمَ لَهَا سَائِلٌ عِنْدَ قَتْلِهَا أَوْ شَقِّ عُضْوٍ مِنْهَا كَالذُّبَابِ، إِنْ لَمْ تُطْرَحْ فِيهِ وَلَمْ تُغَيِّرْهُ؛ وَكَذَا النَّجَاسَةُ الَّتِي لَا يُدْرِكُهَا الطَّرْفُ؛ فَكُلٌّ مِنْهُمَا لَا يُنَجِّسُ الْمَاءَ. وَيُسْتَثْنَى أَيْضاً صُوَرٌ مَذْكُورَاتٌ فِي الْمَبْسُوطَاتِ. وَأَشَارَ لِلْقِسْمِ الثَّانِي مِنَ الْقِسْمِ الرَّابِعِ بِقَوْلِهِ: (أَوْ كَانَ) كَثِيراً (قُلَّتَيْنِ) فَأَكْثَرَ (فَتَغَيَّرَ) يَسِيراً أَوْ كَثِيراً.",
    translationIndo: "Bagian keempat: Air Najis (terkena najis), yaitu ada dua macam. Pertama, air kurang dari dua qullah yang kemasukan benda najis baik sifat air berubah ataupun tidak berubah. Dikecualikan dari hukum ini adalah bangkai yang tidak mengalirkan darah ketika mati atau ketika dibelah tubuhnya seperti lalat, dengan syarat bangkai tersebut tidak sengaja dilemparkan ke dalam air dan tidak merubah sifat air. Juga dikecualikan najis yang sangat halus tidak kasat mata; keduanya tidak menajiskan air. Penulis mengisyaratkan jenis kedua dari bagian keempat dengan ucapannya: 'Atau jika air tersebut banyak (yakni dua qullah atau lebih) lalu sifatnya berubah baik sedikit ataupun banyak.'",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 1 & 4 (Isim Tasniyah & Al-Makhfudhat): Kata 'duuna' (دُونَ) adalah Kalimat Isim berkedudukan sebagai Dharaf (keterangan). Berdasarkan kaidah tarkib Al-Miftah, Isim yang terletak setelah dharaf berposisi sebagai Mudhaf Ilaih yang wajib dibaca Jer. Tanda jer pada kata 'Al-Qullataini' adalah huruf Ya (ي) karena merupakan Isim Tasniyah (kata bermakna ganda).",
    analysisSample: [
      { word: "مَاءٌ", transliteration: "mā'un", translation: "Air", grammarRole: "Mubtada' tsani / Khobar", explanation: "Zat cair murni." },
      { word: "نَجِسٌ", transliteration: "najisun", translation: "yang najis", grammarRole: "Na'at / Sifat", explanation: "Sifat dari air tersebut yang telah tercemari najasah." },
      { word: "الْقُلَّتَيْنِ", transliteration: "al-qullataini", translation: "dua qullah", grammarRole: "Majrur / Tasniyah", explanation: "Istilah kuantitas volume air, dalam bentuk mu'tsanna/dual ditandai huruf ya dan nun." }
    ]
  },
  {
    id: "05",
    title: "Bagian - 5",
    subTitle: "Menyamak Kulit Bangkai & Status Najis Tubuh Hewan",
    arabicText: "فَصْلٌ فِي ذِكْرِ شَيْءٍ مِنَ الْأَعْيَانِ الْمُتَنَجِّسَةِ وَمَا يَطْهُرُ مِنْهَا بِالدِّبَاغِ وَمَا لَا يَطْهُرُ. (وَجُلُودُ الْمَيْتَةِ) كُلُّهَا (تَطْهُرُ بِالدِّبَاغِ) سَوَاءٌ فِي ذَلِكَ مَيْتَةُ مَأْكُولِ اللَّحْمِ وَغَيْرِهِ. وَكَيْفِيَّةُ الدَّبْغِ أَنْ يَنْزَعَ فُضُولَ الْجِلْدِ مِمَّا يُعَفِّنُهُ مِنْ دَمٍ وَنَحْوِهِ، بِشَيْءٍ حَرِيفٍ كَعَفْصٍ, وَلَوْ كَانَ الْحَرِيفُ نَجِساً كَذَرْقِ حَمَامٍ كَفَى فِي الدَّبْغِ (إِلَّا جِلْدَ الْكَلْبِ وَالْخِنْزِيرِ وَمَا تَوَلَّدَ مِنْهُمَا أَوْ مِنْ أَحَدِهِمَا) مَعَ حَيَوَانٍ طَاهِرٍ، فَلَا يَطْهُرُ بِالدِّبَاغِ. وَكَذَا الْمَيْتَةُ أَيْضاً نَجِسَةٌ. وَأُرِيدَ بِهَا الزَّائِلَةُ الْحَيَاةُ (وَعَظْمُ الْمَيْتَةِ وَشَعْرُهَا نَجِسٌ) بِغَيْرِ ذَكَاةٍ شَرْعِيَّةٍ； فَلَا يُسْتَثْنَى حِينَئِذٍ جَنِينُ الْمُذَكَّاةِ إِذَا خَرَجَ مِنْ بَطْنِ أُمِّهِ مَيْتاً، لِأَنَّ ذَكَاتَهُ فِي ذَكَاةِ أُمِّهِ، وَكَذَا غَيْرُهُ مِنَ الْمُسْتَثْنَيَاتِ الْمَذْكُورَةِ فِي الْمَبْسُوطَاتِ. ثُمَّ اسْتَثْنَى مِنْ شَعْرِ الْمَيْتَةِ قَوْLَهُ: (إِلَّا الْآدَمِيَّ) أَيْ فَإِنَّ شَعْرَهُ طَاهِرٌ كَمَيْتَتِهِ.",
    translationIndo: "Pasal yang menjelaskan sebagian benda najis, benda yang bisa suci dengan disamak, dan benda yang tidak bisa suci. Kulit bangkai semuanya bisa suci dengan di samak (baik hewan yang halal dimakan ataupun tidak). Tata cara menyamak adalah dengan membersihkan sisa-sisa lendir/daging yang menempel pada kulit yang membuatnya busuk (seperti sisa darah dsb) menggunakan zat yang kelat/asam seperti buah majakani, meskipun zat tersebut najis seperti kotoran burung merpati sudah mencukupi dalam menyamak. Kecuali kulit anjing dan babi serta peranakan dari keduanya atau salah satunya dengan hewan suci, maka mutlak tidak bisa suci dengan disamak. Adapun tulang bangkai dan bulunya adalah najis jika mati tanpa disembelih secara syar'i. Dikecualikan bulu/rambut manusia, karena jasad manusia hukumnya suci baik dalam keadaan hidup maupun mati.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 2 & 4 (Jamak Taksir & Idhafah): Kata 'juluudu' adalah Isim Jamak Taksir (bentuk jamak yang pecah dari mufrod-nya 'jildun'). Berposisi sebagai Mubtada' dan disandarkan (idhafah) pada 'al-maitati' sebagai Mudhaf Ilaih yang majrur dengan kasrah. Karena dijadikan Mudhaf, kata 'juluud' tidak boleh ditanwin. Fi'il 'tathhuru' berkedudukan sebagai Khobar Jumlah yang menyempurnakan ma'na mubtada' tersebut.",
    analysisSample: [
      { word: "جُلُودُ", transliteration: "julūdu", translation: "Kulit-kulit", grammarRole: "Mubtada' Jamak Taksir", explanation: "Merupakan isim jamak berharakat rafa' tanpa alif lam karena bersambung membentuk mudhaf." },
      { word: "الْمَيْتَةِ", transliteration: "al-maitati", translation: "bangkai", grammarRole: "Mudhaf Ilaih", explanation: "Isim berharakat majrur kasrah, menunjukkan keterangannya milik bangkai." },
      { word: "تَطْهُرُ", transliteration: "taṭhuru", translation: "bisa suci", grammarRole: "Fi'il Mudhari' / Khobatul Jumlah", explanation: "Kalimat kerja aktif perempuan (orang ketiga tunggal) yang menjadi penjelas subjek (khobar)." }
    ]
  },
  {
    id: "06",
    title: "Bagian - 6",
    subTitle: "Hukum Bejana Emas & Perak Serta Batasan Tambalan",
    arabicText: "فَصْلٌ فِي بَيَانِ مَا يَحْرُمُ اسْتِعْمَالُهُ مِنَ الْأَعْيَانِ وَمَا يَجُوزُ. وَبَدَأَ بِالْأَوَّلِ فَقَالَ: (وَلَا يَجُوزُ) فِي غَيْرِ ضَرُورَةٍ لِرَجُلٍ أَوْ امْرَأَةٍ (اسْتِعْمَالُ) شَيْءٍ مِنْ (أَوَانِي الذَّهَبِ وَالْفِضَّةِ)، لَا فِي أَكْلٍ وَلَا فِي شُرْبٍ وَلَا غَيْرِهِمَا； وَكَمَا يَحْرُمُ اسْتِعْمَالُ مَا ذُكِرَ يَحْرُمُ اتِّخَاذُهُ مِنْ غَيْرِ اسْتِعْمَالٍ فِي الْأَصَحِّ. وَيُحْرَمُ أَيْضاً الْإِنَاءُ الْمَطْلِيُّ بِذَهَبٍ أَوْ فِضَّةٍ إِنْ حَصَلَ مِنَ الطِّلَاءِ شَيْءٌ بِعَرْضِهِ عَلَى النَّارِ. (وَيَجُوزُ اسْتِعْمَالُ) إِنَاءٍ (غَيْرِهِمَا) أَيْ غَيْرِ الذَّهَبِ وَالْفِضَّةِ (مِنَ الْأَوَانِي) النَّفِيسَةِ كَإِنَاءِ يَاقُوتٍ. وَيُحْرَمُ الْإِنَاءُ الْمُضَبَّبُ بِضَبَّةِ فِضَّةٍ كَبِيرَةٍ عُرْفاً لِزِينَةٍ； فَإِنْ كَانَتْ كَبِيرَةً لِحَاجَةٍ جَازَ مَعَ الْكَرَاهَةِ، أَوْ صَغِيرَةً عُرْفاً لِزِينَةٍ كُرِهَتْ، أَوْ لِحَاجَةٍ فَلَا تُكْرَهُ. أَمَّا ضَبَّةُ الذَّهَبِ فَتُحْرَمُ مُطْلَقاً، كَمَا صَحَّحَهُ النَّوَوِيُّ.",
    translationIndo: "Pasal yang menerangkan bejana-bejana yang haram dan boleh digunakan. Memulai dengan yang diharamkan, penulis berkata: 'Tidak diperbolehkan (kecuali darurat) bagi laki-laki maupun perempuan menggunakan bejana yang terbuat dari emas dan perak, baik untuk makan, minum, maupun penggunaan lainnya.' Serta sebagaimana menggunakannya itu haram, menyimpannya saja tanpa menggunakannya pun hukumnya haram menurut pendapat yang paling shahih. Diharamkan juga wadah yang disepuh emas/perak jika sepuhan tersebut bisa terkelupas saat dibakar di atas api. Dan diperbolehkan menggunakan wadah selain emas dan perak, semisal bejana berharga seperti Yakut. Diharamkan wadah yang ditambal dengan perak berukuran besar untuk hiasan; jika besar karena butuh maka makruh, jika kecil untuk hiasan maka makruh, jika kecil karena butuh maka tidak makruh. Adapun tambalan emas hukumnya haram secara mutlak.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 3 & 4 (Skema Fi'il & Fa'il): Kata 'yajuuzu' (يَجُوزُ) adalah Fi'il Mudhari' Mu'rob (Lafdhi) karena tidak bersambung dengan nun taukid maupun nun niswah. Isim setelahnya, yaitu 'isti'maalu' (اسْتِعْمَالُ) yang merupakan Isim Masdar, berkedudukan sebagai Fa'il (pelaku) yang dibaca Rofa' dengan tanda dhommah murni (Marfu'atul Asma').",
    analysisSample: [
      { word: "لَا يَجُوزُ", transliteration: "lā yajūzu", translation: "tidak diperbolehkan", grammarRole: "La Nafiyah + Fi'il", explanation: "La peniadaan hukum kelayakan yang diikuti kata kerja aktif masa sekarang." },
      { word: "الذَّهَبِ", transliteration: "ad-dhahabi", translation: "emas", grammarRole: "Mudhaf ilaih", explanation: "Sebutan logam mulia nomor satu berharakat kasrah." },
      { word: "الْأَوَانِي", transliteration: "al-awānī", translation: "bejana / wadah", grammarRole: "Isim Majrur", explanation: "Menerangkan bentuk jamak taksir dari kata ina'un (wadah)." }
    ]
  },
  {
    id: "07",
    title: "Bagian - 7",
    subTitle: "Hukum Bersiwak, Keutamaan Serta Waktu Bersiwak",
    arabicText: "فَصْلٌ فِي اسْتِعْمَالِ آلَةِ السِّوَاكِ. وَهُوَ مِنْ سُنَنِ الْوُضُوءِ； وَيُطْلَقُ السِّوَاكُ أَيْضاً عَلَى مَا يُسْتَاكُ بِهِ مِنْ أَرَاكٍ وَنَحْوِهِ. (وَالسِّوَاكُ مُسْتَحَبٌّ فِي كُلِّ حَالٍ) وَلَا يُكْرَهُ تَنْزِيهاً (إِلَّا بَعْدَ الزَّوَالِ لِلصَّائِمِ) فَرْضاً أَوْ نَفْلاً； وَتَزُولُ الْكَرَاهَةُ بِغُرُوبِ الشَّمْسِ. وَاخْتَارَ النَّوَوِيُّ عَدَمَ الْكَرَاهَةِ مُطْلَقاً. (وَهُوَ) أَيْ السِّوَاكُ (فِي ثَلَاثَةِ مَوَاضِعَ أَشَدُّ اسْتِحْبَاباً) مِنْ غَيْرِهَا； أَحَدُهَا: قِيلَ: هُوَ سُكُوتٌ طَوِيلٌ. وَقِيلَ: هُوَ تَرْكُ الْأَكْلِ. وَإِنَّمَا قَالَ (عِنْدَ تَغَيُّرِ الْفَمِ مِنْ أَزْمٍ) لِيَشْتَمِلَ تَغَيُّرَ الْفَمِ بِغَيْرِ أَزْمٍ، كَأَكْلِ ذِي رِيحٍ كَرِيهٍ مِنْ ثُومٍ وَبَصَلٍ وَغَيْرِهِمَا； (وَ) (وَغَيْرِهِ) الثَّانِي (عِنْدَ الْقِيَامِ) أَيْ الِاسْتِيقَاظِ (مِنَ النَّوْمِ)； (وَ) الثَّالثُ (عِنْدَ الْقِيَامِ إِلَى الصَّلَاةِ)، فَرْضاً أَوْ نَفْلاً. وَيَتَأَكَّدُ أَيْضاً فِي غَيْرِ الثَّلَاثَةِ الْمَذْكُورَةِ مِمَّا هُوَ مَذْكُورٌ فِي الْمَطْوَلَاتِ كَقِرَاءَةِ الْقُرْآنِ, وَاصْفِرَارِ الْأَسْنَانِ. وَيُسَنُّ... أَنْ يَنْوِيَ بِالسِّوَاكِ السُّنَّةَ； وَأَنْ يَسْتَاكَ بِيَمِينِهِ، وَيَبْدَأَ بِالْجَانِبِ الْأَيْمَنِ مِنْ فَمِهِ، وَأَنْ يُمِرَّهُ عَلَى سَقْفِ حَلْقِهِ إِمْرَاراً لَطِيفاً، وَعَلَى كَرَاسِيِّ أَضْرَاسِهِ.",
    translationIndo: "Pasal tentang bersiwak. Bersiwak termasuk perbuatan sunah wudhu. Istilah siwak juga digunakan untuk alatnya yaitu kayu arok dsb. Bersiwak dihukumi sunah dalam setiap keadaan dan tidak makruh, kecuali bagi orang yang berpuasa (baik puasa wajib/sunah) setelah tergelincir matahari (waktu Dzuhur), kemakruhan ini hilang dengan tenggelamnya matahari. Namun Imam Nawawi memilih pendapat tidak makruh secara mutlak. Bersiwak sangat dianjurkan pada tiga kondisi: Pertama, saat berubahnya bau mulut karena diam terlalu lama atau meninggalkan makan. Kedua, saat bangun tidur. Ketiga, saat hendak melaksanakan shalat, baik shalat fardhu maupun sunah. Disunahkan niat bersiwak, memegang siwak dengan tangan kanan, memulai dari sisi kanan mulut, serta menggosok langit-langit mulut dan gigi geraham secara lembut.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 2 & 4 (Kesesuaian Mubtada'-Khobar): Kata 'As-Siwaaku' adalah Isim Ma'rifah (karena ber-Alif Lam) berkedudukan sebagai Mubtada'. Khobar-nya adalah kata 'Mustahabbun' (Isim Nakirah). Keduanya selaras dalam hal Mudzakkar (laki-laki) dan Mufrad (tunggal), berharokat Rofa' ditandai dhommah.",
    analysisSample: [
      { word: "السِّوَاكُ", transliteration: "as-siwāku", translation: "Bersiwak itu", grammarRole: "Mubtada'", explanation: "Isim Mufrad (Tunggal) berharakat rafa' dhommah." },
      { word: "مُسْتَحَبٌّ", transliteration: "mustaḥabbun", translation: "hukumnya sunnah", grammarRole: "Khobar", explanation: "Keterangan sunat dianjurkan yang menjelaskan hukum siwak." },
      { word: "لِلصَّائِمِ", transliteration: "liṣ-ṣā'imi", translation: "bagi orang puasa", grammarRole: "Majrur", explanation: "Huruf li (jarr) bertemu isim fail as-soim." }
    ]
  },
  {
    id: "08",
    title: "Bagian - 8",
    subTitle: "Enam Fardhu (Rukun Utama) Dalam Berwudhu",
    arabicText: "فَصْلٌ فِي فُرُوضِ الْوُضُوءِ. وَهُوَ بِضَمِّ الْوِاوِ - فِي الْأَشْهَرِ - اسْمٌ لِلْفِعْلِ، وَهُوَ الْمُرَادُ هُنَا؛ وَبِفَتْحِ الْوِاوِ اسْمٌ لِمَا يَتَوَضَّأُ بِهِ. وَيَشْتَمِلُ الْأَوَّلُ عَلَى فُرُوضٍ وَسُنَنٍ. وَذَكَرَ الْمُصَنِّفُ الْفُرُوضَ فِي قَوْلِهِ: (وَفُرُوضُ الْوُضُوءِ سِتَّةُ أَشْيَاءَ): أَحَدُهَا (النِّيَّةُ). وَحَقِيقَتُهَا شَرْعاً قَصْدُ الشَّيْءِ مُقْتَرِناً بِفِعْلِهِ； فَإِنْ تَرَاخَى عَنْهُ سُمِّيَ عَزْماً. وَتَكُونُ النِّيَّةُ (عِنْدَ غَسْلِ) أَوَّلِ جُزْءٍ مِنَ (الْوَجْهِ) أَيْ مُقْتَرِنَةً بِذَلِكَ الْجُزْءِ، لَا بِجَمِيعِهِ، وَلَا بِمَا قَبْلَهُ، وَلَا بِمَا بَعْدَهُ.",
    translationIndo: "Pasal tentang kewajiban wudhu. Kata wudhu dengan dhommah huruf wawu menurut pendapat terpopuler adalah nama untuk perbuatannya (yaitu membasuh organ), sedangkan dengan fathah berarti air yang digunakan untuk berwudhu. Rukun/Fardhu wudhu ada 6 macam: Pertama, Niat. Hakikat niat secara syara' adalah menyengaja melakukan sesuatu berbarengan dengan awal perbuatannya; jika niat mendahului perbuatan maka dinamakan azam (tekad). Letak niat harus berbarengan (saat membasuh) bagian pertama dari wajah, tidak didepan dan tidak diletakkan setelah selesai membasuh wajah.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 2 & 4 (Isim Ghairu Munsharif & Idhafah): Kata 'furuudu' adalah Mubtada' Jamak Taksir (bukan tanwin karena bersambung membentuk mudhaf ke 'al-wudhuu-i'). Khobar-nya adalah 'sittatu' yang di-idhofahkan ke 'asy-ya-a' (isim makhfudh/majrur). Kata 'asy-ya-a' dibaca Majrur dengan tanda fathah (bukan kasrah) karena berstatus Isim Ghairu Munsharif (tidak menerima tanwin).",
    analysisSample: [
      { word: "فُرُوضُ", transliteration: "furūḍu", translation: "Kewajiban-kewajiban", grammarRole: "Mubtada' Jamak Taksir", explanation: "Bentuk jamak dari fardhun." },
      { word: "الْوُضُوءِ", transliteration: "al-wuḍū'i", translation: "Wudhu", grammarRole: "Mudhaf Ilaih", explanation: "Sesuai gramatika pesantren, ini majrur dibaca kasrah." },
      { word: "سِتَّةُ", transliteration: "sittatu", translation: "adalah enam", grammarRole: "Khobar", explanation: "Pembatas rukun utama yaitu khobar mubtada." }
    ]
  },
  {
    id: "09",
    title: "Bagian - 9",
    subTitle: "Sepuluh Perkara Sunnah Menyempurnakan Wudhu",
    arabicText: "أَيْ: الْوُضُوءُ (عَشَرَةُ أَشْيَاءَ)، وَفِي بَعْضِ نُسَخِ الْمَتْنِ: «عَشْرُ (وَسُنَنُهُ) خِصَالٌ»: (1 التَّسْمِيَةُ) أَوَّلُهُ. وَأَقَلُّهَا بِسْمِ اللَّهِ، وَأَكْمَلُهَا بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ؛ فَإِنْ تَرَكَ التَّسْمِيَةَ أَوَّلَهُ أَتَى بِهَا فِي أَثْنَائِهِ؛ فَإِنْ فَرِغَ مِنَ الْوُضُوءِ لَمْ يَأْتِ بِهَا. (2 وَغَسْلُ الْكَفَّيْنِ) إِلَى الْكُوعَيْنِ قَبْلَ الْمَضْمَضَةِ، وَيَغْسِلُهُمَا ثَلَاثاً إِنْ تَرَدَّدَ فِي طُهْرِهِمَا (قَبْلَ إِدْخَالِهِمَا الْإِنَاءَ) الْمُشْتَمِلِ عَلَى مَاءِ دُونَ الْقُلَّتَيْنِ؛ فَإِنْ لَمْ يَغْسِلْهُمَا كُرِهَ لَهُ غَمْسُهُمَا فِي الْإِنَاءِ، وَإِنْ تَيَقَّنَ طُهْرَهُمَا لَمْ يُكْرَهْ غَمْسُهُمَا. (3 وَالْمَضْمَضَةُ) بَعْدَ غَسْلِ الْكَفَّيْنِ. وَيَحْصُلُ أَصْلُ السُّنَّةِ فِيهَا بِإِدْخَالِ الْمَاءِ فِي الْفَمِ سَوَاءٌ أَدَارَهُ فِيهِ وَمَجَّهُ أَمْ لَا؛ فَإِنْ أَرَادَ الْأَكْمَلَ مَجَّهُ.",
    translationIndo: "Ada sepuluh perkara sunah wudhu: Pertama, Membaca basmalah di permulaan wudhu. Sekurang-kurangnya adalah 'Bismillah', dan sempurnanya adalah 'Bismillahirrahmanirrahim'. Jika lupa membacanya di awal wudhu, ia bisa membacanya di tengah wudhu; namun jika wudhu sudah selesai, disunahkan tidak perlu membacanya lagi. Kedua, Membasuh dua belah telapak tangan hingga pergelangan sebelum berkumur sebanyak 3 kali jika ragu akan kesuciannya sebelum dimasukkan ke dalam wadah air yang volumenya kurang dari dua qullah. Ketiga, Berkumur setelah membasuh telapak tangan. Kesunahan berkumur sudah dianggap sah dengan memasukkan air ke dalam mulut, baik air itu diputar-putar lalu dimuntahkan ataupun tidak; namun yang paling utama adalah dengan memuntahkannya kembali.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 4 & Tashrif (Mubtada' Mahdzuf & Isim Masdar): Kata 'Asyuratun' berkedudukan sebagai Khobar dari Mubtada' yang dibuang (Mahdzuf), takdirnya adalah 'wa sunanuhu asyaratu asy-ya-a'. Dari sudut pandang ilmu Sharaf (Tashrif Al-Miftah), kata 'Ghaslu' dan 'Madhmadhatu' merupakan bentuk Isim Masdar ghoiru mim dari kata kerja tsulatsi mujarrad (ghasala) dan ruba'i mujarrad (madhmadha).",
    analysisSample: [
      { word: "التَّسْمِيَةُ", transliteration: "at-tasmiyatu", translation: "Membaca Bismillah", grammarRole: "Mubtada' / Badal", explanation: "Isim masdar yang diawali alif lam berkas jarr masdar." },
      { word: "أَوَّلَهُ", transliteration: "awwalahu", translation: "di permulaannya", grammarRole: "Dharaf Zaman", explanation: "Kandungan waktu yang membatasi tindakan." }
    ]
  },
  {
    id: "10",
    title: "Bagian - 10",
    subTitle: "Kewajiban Istinja' (Bersuci) & Tata Adabnya",
    arabicText: "فَصْلٌ فِي الِاسْتِنْجَاءِ وَآدَابِ قَاضِي الْحَاجَةِ. (وَالِاسْتِنْجَاءُ) - وَهُوَ «مِنْ نَجَوْتُ الشَّيْءَ»، أَيْ قَطَعْتُهُ، فَكَأَنَّ الْمُسْتَنْجِيَ يَقْطَعُ بِهِ الْأَذَى عَنْ نَفْسِهِ - (وَاجِبٌ مِنْ) خُرُوجِ (الْبَوْلِ وَالْغَائِطِ) بِالْمَاءِ أَوْ الْحَجَرِ وَمَا فِي مَعْنَاهُ مِنْ كُلِّ جَامِدٍ طَاهِرٍ قَالِعٍ غَيْرِ مُحْتَرَمٍ، (وَ) لَكِنْ (الْأَفْضَلُ أَنْ يَسْتَنْجِيَ) أَوَّLَا (بِالْأَحْجَارِ ثُمَّ يُتْبِعُهَا) ثَانِياً (بِالْمَاءِ). وَالْوَاجِبُ ثَلَاثُ مَسَحَاتٍ وَلَوْ بِثَلَاثَةِ أَطْرَافِ حَجَرٍ وَاحِدٍ. (وَيَجُوزُ أَنْ يَقْتَصِرَ) الْمُسْتَنْجِي (عَلَى الْمَاءِ أَوْ عَلَى ثَلَاثَةِ أَحْجَارٍ يُنَقِّي بِهِنَّ الْمَحَلَّ) إِنْ حَصَلَ الْإِنْقَاءُ بِهَا، وَإِلَّا زَادَ عَلَيْهَا حَتَّى يَنْقَى. وَيُسَنُّ بَعْدَ ذَلِكَ التَّثْلِيثُ. (فَإِذَا أَرَادَ الِاقْتِصَارَ عَلَى أَحَدِهِمَا، فَالْمَاءُ أَفْضَلُ) لِأَنَّهُ يُزِيلُ عَيْنَ النَّجَاسَةِ وَأَثَرَهَا.",
    translationIndo: "Pasal tentang istinja' (bersuci setelah buang air) dan adab buang hajat. Kata istinja' berasal dari kata 'najautus syai' yang bermakna 'saya memotong sesuatu', seolah-olah orang yang beristinja' memutus kotoran dari dirinya. Istinja' hukumnya wajib dari keluarnya air seni (kemih) maupun kotoran besar (tinja) menggunakan air atau batu dan benda keras, suci, kesat/dapat membersihkan, serta tidak dimuliakan. Cara terbaik adalah istinja' terlebih dahulu menggunakan tiga batu kemudian disusul dengan dibilas air. Diperbolehkan juga mencukupkan hanya dengan air saja atau dengan tiga batu untuk mensucikan tempat keluarnya najis sampai bersih. Jika ingin memilih salah satu saja, maka menggunakan air lebih utama karena air dapat melenyapkan wujud najis beserta bekas-bekasnya.",
    explanation: "Panduan Al-Miftah Lil Ulum Jilid 1, 3 & 4 (Isim Mabni, Amil Nawasib & Khobar): Kata 'Al-Istinja-u' adalah Isim Mu'rob berkedudukan sebagai Mubtada'. Kata 'Waajibun' bertindak sebagai Khobar-nya yang menunjukkan kelengkapan hukum. Kata 'yastanjia' (يَسْتَنْجِيَ) adalah Fi'il Mudhari' berstatus Mansub (nasab) karena kemasukan Amil Nawasib berupa huruf 'an' (أَنْ), ditandai dengan fathah di akhir huruf ya.",
    analysisSample: [
      { word: "الْأَفْضَلُ", transliteration: "al-afḍalu", translation: "adalah yang paling utama", grammarRole: "Mubtada' Mu'akhor / Isim Tafdhil", explanation: "Bentuk keutamaan superlatif." },
      { word: "بِالْمَاءِ", transliteration: "bil-mā'i", translation: "dengan air", grammarRole: "Jarr Majrur", explanation: "Kombinasi huruf ba' yang bermakna alat wujud dengan isim majrur mutlaq." }
    ]
  }
];
